#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-HTML-Lint
Version  : 2.32
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/P/PE/PETDANCE/HTML-Lint-2.32.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PE/PETDANCE/HTML-Lint-2.32.tar.gz
Summary  : 'check for HTML errors in a string or file'
Group    : Development/Tools
License  : Artistic-2.0
Requires: perl-HTML-Lint-bin = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(HTML::Entities)
BuildRequires : perl(HTML::Parser)
BuildRequires : perl(HTML::Tagset)

%description
# HTML::Lint
* Linux [![Build Status](https://api.travis-ci.org/petdance/html-lint.svg?branch=dev)](https://travis-ci.org/petdance/html-lint)
* [CPAN Testers](http://cpantesters.org/distro/H/html-lint.html)

%package bin
Summary: bin components for the perl-HTML-Lint package.
Group: Binaries

%description bin
bin components for the perl-HTML-Lint package.


%package dev
Summary: dev components for the perl-HTML-Lint package.
Group: Development
Requires: perl-HTML-Lint-bin = %{version}-%{release}
Provides: perl-HTML-Lint-devel = %{version}-%{release}

%description dev
dev components for the perl-HTML-Lint package.


%prep
%setup -q -n HTML-Lint-2.32

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.26.1/HTML/Lint.pm
/usr/lib/perl5/vendor_perl/5.26.1/HTML/Lint/Error.pm
/usr/lib/perl5/vendor_perl/5.26.1/HTML/Lint/HTML4.pm
/usr/lib/perl5/vendor_perl/5.26.1/HTML/Lint/Parser.pm
/usr/lib/perl5/vendor_perl/5.26.1/Test/HTML/Lint.pm

%files bin
%defattr(-,root,root,-)
/usr/bin/weblint

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/HTML::Lint.3
/usr/share/man/man3/HTML::Lint::Error.3
/usr/share/man/man3/HTML::Lint::HTML4.3
/usr/share/man/man3/HTML::Lint::Parser.3
/usr/share/man/man3/Test::HTML::Lint.3
